name: Maven Build and Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build
        run: mvn -B clean compile
      - name: Run ExcelMonitor
        run: mvn exec:java -Dexec.mainClass=ScienceFair.ScienceFair.ExcelMonitor -Dexec.args="src/main/java/ScienceFair/ScienceFair/ScienceFair.xlsx"
